"""clade-add-peer — add a new peer to an existing setup-server project.

Surgical addition: generates new HMAC secrets, updates every existing peer's
yaml, appends to tokens.json, writes the new peer's yaml + start/chat scripts +
workdir, then signals the relay and setup-server to reload their in-memory
state. Existing daemons hot-reload the peer allowlist via config_watcher_loop
(v1.7.0) — only the new peer's daemon needs to be started manually.

Usage:
    clade-add-peer <peer_id> "<display_name>" "<role>" [--team NAME]...

Example:
    clade-add-peer designer "Mira - UX designer" \\
        "You are Mira, UX designer. Specialty: Figma, design systems." \\
        --team everyone --team engineering
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import sys
from pathlib import Path
from typing import Any

import httpx
import yaml


def _find_active_project(setup_base: Path) -> Path:
    """Locate the single active project dir. Error if zero or more than one."""
    if not setup_base.exists():
        sys.exit(f"Error: setup-server data dir not found: {setup_base}")
    projects = sorted(
        p for p in setup_base.iterdir()
        if p.is_dir() and (p / "setup.json").exists()
    )
    if not projects:
        sys.exit(
            f"Error: no active setup project found in {setup_base}.\n"
            f"Run ./scripts/start-setup-server.sh --quickstart first."
        )
    if len(projects) > 1:
        listing = "\n  ".join(str(p) for p in projects)
        sys.exit(
            f"Error: multiple setup projects in {setup_base}; ambiguous which to extend:\n  {listing}\n"
            f"Pass --setup-data-dir or pick one and delete the others."
        )
    return projects[0]


def _write_yaml(path: Path, data: dict[str, Any]) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False))
    tmp.chmod(0o600)
    tmp.replace(path)


def _write_json_secure(path: Path, data: Any) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2) + ("\n" if isinstance(data, dict) else ""))
    tmp.chmod(0o600)
    tmp.replace(path)


def _render_start_sh(peer_id: str, display_name: str, agent_dir: Path) -> str:
    """Minimal start-<peer>.sh that matches the install.sh.j2 template output."""
    return f"""#!/bin/bash
# Clade A2A daemon start script for peer '{peer_id}' ({display_name})
# Generated by clade-add-peer.

set -e
cd "$(dirname "$0")"

CLADE_REPO_DIR="${{CLADE_REPO_DIR:-/opt/clade-a2a}}"
CLADE_PYTHON="$CLADE_REPO_DIR/.venv/bin/python"

if [[ ! -x "$CLADE_PYTHON" ]]; then
  echo "Error: clade-a2a not installed at $CLADE_REPO_DIR"
  exit 1
fi

export CLADE_CONFIG="$(pwd)/{peer_id}.yaml"

if [[ ! -f "$CLADE_CONFIG" ]]; then
  echo "Error: config not found at $CLADE_CONFIG"
  exit 1
fi

echo "Starting Clade A2A daemon as '{peer_id}'..."
echo "  Config:  $CLADE_CONFIG"

exec "$CLADE_PYTHON" -m agent.daemon "$@"
"""


def _render_chat_sh(peer_id: str, display_name: str, relay_url: str, agent_dir: Path) -> str:
    """Minimal chat-<peer>.sh — opens an interactive Claude session pointed at
    the workdir, with the full clade_* tool allow-list pre-approved."""
    workdir = agent_dir / f"workdir-{peer_id}"
    tools = ",".join(
        f"mcp__clade__{name}"
        for name in (
            "clade_message", "clade_send", "clade_ask", "clade_inbox", "clade_reply",
            "clade_outbox_status", "clade_peers", "clade_broadcast",
            "clade_task", "clade_task_update", "clade_task_status", "clade_task_list",
        )
    )
    return f"""#!/bin/bash
# Clade A2A interactive Claude session for peer '{peer_id}' ({display_name})
# Generated by clade-add-peer.

set -e
cd "$(dirname "$0")"
WORKDIR="{workdir}"
MY_ID="{peer_id}"
MY_NAME="{display_name}"
RELAY_URL="{relay_url}"

if ! command -v claude > /dev/null; then
  echo "Error: 'claude' command not found in PATH"
  exit 1
fi

if [[ ! -d "$WORKDIR" ]]; then
  echo "Error: workdir not found at $WORKDIR"
  exit 1
fi

SYSTEM_PROMPT="You help the user talk over the Clade A2A network.
USER is peer '${{MY_NAME}}' (ID: ${{MY_ID}}). Relay: ${{RELAY_URL}}.

Use clade_peers() to see who is online right now. Use clade_message(to=..., content=...) for direct asks, clade_broadcast(to_team=..., content=...) for team-wide, clade_task(to=..., brief=...) for async delegation. Be terse — one sentence for trivial info, no tables for <5 items, no unsolicited follow-up offers."

cd "$WORKDIR"
exec claude --append-system-prompt "$SYSTEM_PROMPT" --permission-mode acceptEdits --allowedTools "{tools}"
"""


def _render_mcp_config(peer_id: str, agent_dir: Path) -> str:
    """workdir/.mcp.json — same shape as setup-server's mcp-config.json.j2."""
    return json.dumps({
        "mcpServers": {
            "clade": {
                "command": "/opt/clade-a2a/.venv/bin/python",
                "args": ["/opt/clade-a2a/agent/main.py"],
                "env": {"CLADE_CONFIG": str(agent_dir / f"{peer_id}.yaml")},
            }
        }
    }, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="clade-add-peer",
        description="Add a new peer to an existing setup-server project (surgical, no daemon restarts).",
    )
    parser.add_argument("peer_id", help="Slug like 'designer'; must start with a letter, alnum/dash/underscore only")
    parser.add_argument("display_name", help="Display name shown to other agents")
    parser.add_argument("role", help="Role prompt — what this agent does")
    parser.add_argument("--team", action="append", default=[],
                        help="Add this peer to a team (can be repeated); team is auto-created if missing")
    parser.add_argument("--agent-dir", default=os.path.expanduser("~/clade-agent"),
                        help="Local dir where peer yamls + scripts live (default: ~/clade-agent)")
    parser.add_argument("--setup-data-dir",
                        default=os.environ.get("CLADE_SETUP_DATA_DIR",
                                               os.path.expanduser("~/.clade/setup-server")),
                        help="setup-server data dir (default: ~/.clade/setup-server)")
    parser.add_argument("--setup-server-url", default="http://127.0.0.1:8000",
                        help="setup-server URL for /admin/reload (default: http://127.0.0.1:8000)")
    parser.add_argument("--no-reload", action="store_true",
                        help="Skip reloading relay + setup-server (useful when they aren't running)")
    args = parser.parse_args()

    pid = args.peer_id.strip()
    if not pid or not pid[0].isalpha() or not all(c.isalnum() or c in "-_" for c in pid):
        sys.exit("Invalid peer_id — must start with a letter, alnum/dash/underscore only")

    project_dir = _find_active_project(Path(args.setup_data_dir))
    agent_dir = Path(args.agent_dir).expanduser()
    setup = json.loads((project_dir / "setup.json").read_text())
    tokens = json.loads((project_dir / "tokens.json").read_text())

    existing_peer_ids = [p["peer_id"] for p in setup["peers"]]
    if pid in existing_peer_ids:
        sys.exit(f"Error: peer '{pid}' already exists in this setup.")

    print(f"Adding peer '{pid}' to setup '{setup['project_name']}' ({project_dir.name})")
    print(f"  existing peers: {existing_peer_ids}")

    # 1. Generate new secrets
    new_bearer = secrets.token_urlsafe(32)
    new_download_token = secrets.token_urlsafe(24)
    new_pair_secrets: dict[str, str] = {
        other_id: secrets.token_hex(32) for other_id in existing_peer_ids
    }

    # 2. Update every existing yaml (in both project_dir and agent_dir)
    role_short = args.role.strip().split("\n")[0][:200]
    for other_id in existing_peer_ids:
        for base in (agent_dir, project_dir):
            yaml_path = base / f"{other_id}.yaml"
            if not yaml_path.exists():
                continue
            data = yaml.safe_load(yaml_path.read_text()) or {}
            data.setdefault("peers", {})
            entry: dict[str, Any] = {
                "secret": new_pair_secrets[other_id],
                "name": args.display_name,
                "role": role_short,
            }
            data["peers"][pid] = entry
            # Update teams in place
            data.setdefault("teams", {})
            for team in args.team:
                members = data["teams"].setdefault(team, [])
                if pid not in members:
                    members.append(pid)
            _write_yaml(yaml_path, data)
        print(f"  updated {other_id}.yaml")

    # 3. Build the new peer's yaml
    new_peers_dict: dict[str, Any] = {}
    for other_id in existing_peer_ids:
        other_artifact = next(p for p in setup["peers"] if p["peer_id"] == other_id)
        entry = {"secret": new_pair_secrets[other_id]}
        if other_artifact.get("display_name") and other_artifact["display_name"] != other_id:
            entry["name"] = other_artifact["display_name"]
        if other_artifact.get("role"):
            entry["role"] = other_artifact["role"].strip().split("\n")[0][:200]
        new_peers_dict[other_id] = entry

    # Copy the teams structure from any existing yaml (they're all kept in sync)
    combined_teams: dict[str, list[str]] = {}
    for other_id in existing_peer_ids:
        existing_yaml = agent_dir / f"{other_id}.yaml"
        if not existing_yaml.exists():
            existing_yaml = project_dir / f"{other_id}.yaml"
        if existing_yaml.exists():
            data = yaml.safe_load(existing_yaml.read_text()) or {}
            for team_name, members in (data.get("teams") or {}).items():
                combined_teams.setdefault(team_name, list(members))
            break
    # Ensure new peer is in any --team groups (also creates the team if missing)
    for team in args.team:
        members = combined_teams.setdefault(team, [])
        if pid not in members:
            members.append(pid)

    new_yaml_data: dict[str, Any] = {
        "my_id": pid,
        "name": args.display_name,
        "role": args.role.strip(),
        "relay_url": setup["relay_url"],
        "bearer_token": new_bearer,
        "peers": new_peers_dict,
        "audit_db": f"~/.clade/{pid}-audit.db",
        "extra_add_dirs": [],
    }
    if combined_teams:
        new_yaml_data["teams"] = combined_teams

    yaml_text = yaml.dump(new_yaml_data, default_flow_style=False, allow_unicode=True, sort_keys=False)

    # Write to project_dir + agent_dir
    for base in (project_dir, agent_dir):
        base.mkdir(parents=True, exist_ok=True)
        (base / f"{pid}.yaml").write_text(yaml_text)
        (base / f"{pid}.yaml").chmod(0o600)
    print(f"  wrote {pid}.yaml")

    # 4. Append to tokens.json
    tokens[new_bearer] = pid
    _write_json_secure(project_dir / "tokens.json", tokens)
    print(f"  appended bearer to tokens.json")

    # 5. Update setup.json — needed so setup-server's _load_setups picks it up on restart
    setup["peers"].append({
        "peer_id": pid,
        "display_name": args.display_name,
        "role": args.role,
        "download_token": new_download_token,
        "bearer_token": new_bearer,
        "yaml_path": str(project_dir / f"{pid}.yaml"),
        "yaml_content": yaml_text,
    })
    _write_json_secure(project_dir / "setup.json", setup)
    print(f"  updated setup.json")

    # 6. Write the new peer's start-, chat-, mcp-config files in agent_dir
    if agent_dir.exists():
        (agent_dir / f"start-{pid}.sh").write_text(_render_start_sh(pid, args.display_name, agent_dir))
        (agent_dir / f"start-{pid}.sh").chmod(0o755)
        (agent_dir / f"chat-{pid}.sh").write_text(_render_chat_sh(pid, args.display_name, setup["relay_url"], agent_dir))
        (agent_dir / f"chat-{pid}.sh").chmod(0o755)
        workdir = agent_dir / f"workdir-{pid}"
        workdir.mkdir(exist_ok=True)
        (workdir / ".mcp.json").write_text(_render_mcp_config(pid, agent_dir))
        # Update start.sh / chat.sh symlinks to point to the new peer (backward compat)
        for link_name in ("start.sh", "chat.sh"):
            link_path = agent_dir / link_name
            if link_path.is_symlink() or not link_path.exists():
                target = f"{link_name.replace('.sh', '')}-{pid}.sh"
                if link_path.exists() or link_path.is_symlink():
                    link_path.unlink()
                link_path.symlink_to(target)
        print(f"  wrote start-{pid}.sh, chat-{pid}.sh, workdir-{pid}/.mcp.json")

    # 7. Reload relay and setup-server
    if not args.no_reload:
        # Reload relay tokens
        any_bearer = next(iter(tokens))
        try:
            r = httpx.post(f"{setup['relay_url']}/admin/reload-tokens",
                            headers={"Authorization": f"Bearer {any_bearer}"},
                            timeout=5)
            if r.status_code == 200:
                print(f"  relay reloaded: {r.json().get('added')} added")
            else:
                print(f"  WARN: relay reload returned HTTP {r.status_code}: {r.text[:200]}", file=sys.stderr)
        except Exception as e:
            print(f"  WARN: relay reload failed ({type(e).__name__}: {e}); "
                  f"the new peer's daemon will fail with 401 until the relay restarts.", file=sys.stderr)

        # Reload setup-server in-memory state
        try:
            r = httpx.post(f"{args.setup_server_url.rstrip('/')}/admin/reload", timeout=5)
            if r.status_code == 200:
                print(f"  setup-server reloaded: peer_count_delta={r.json().get('peer_count_delta')}")
            else:
                print(f"  WARN: setup-server reload returned HTTP {r.status_code}: {r.text[:200]}", file=sys.stderr)
        except Exception as e:
            print(f"  WARN: setup-server reload failed ({type(e).__name__}: {e}); "
                  f"the web UI will catch up after restart.", file=sys.stderr)

    # 8. Print next steps
    print()
    print("==================================================")
    print(f"Peer '{pid}' added.")
    print("==================================================")
    print()
    print(f"Start the new daemon (new terminal):")
    print(f"  {agent_dir}/start-{pid}.sh --yolo")
    print()
    print(f"Or open an interactive session for it:")
    print(f"  {agent_dir}/chat-{pid}.sh")
    print()
    print("Existing daemons hot-reload the peer allowlist within ~5s (v1.7.0+ config_watcher_loop)")
    print("— no need to restart them.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
