"""Reusable peer-management operations: add / update / remove / set-teams.

Used by both the CLI (clade-add-peer) and the setup-server's REST endpoints.
Each op is idempotent where possible and returns a dict describing what
changed. Optional `relay_url_for_reload` / `setup_server_url_for_reload`
trigger out-of-band reloads (skip these from in-process setup-server callers
that swap state directly).
"""

from __future__ import annotations

import json
import os
import secrets
from pathlib import Path
from typing import Any

import httpx
import yaml


# ---- yaml / json helpers ----

def _write_yaml(path: Path, data: dict[str, Any]) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False))
    tmp.chmod(0o600)
    tmp.replace(path)


def _write_json_secure(path: Path, data: Any) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2) + ("\n" if isinstance(data, dict) else ""))
    tmp.chmod(0o600)
    tmp.replace(path)


def _read_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text()) or {}


# ---- script rendering (mirror of install.sh.j2 + chat.sh.j2 minimal output) ----

CLADE_TOOLS = ",".join(
    f"mcp__clade__{n}" for n in (
        "clade_message", "clade_send", "clade_ask", "clade_inbox", "clade_reply",
        "clade_outbox_status", "clade_peers", "clade_broadcast",
        "clade_task", "clade_task_update", "clade_task_status", "clade_task_list",
    )
)


def _render_start_sh(peer_id: str, display_name: str) -> str:
    return f"""#!/bin/bash
# Clade A2A daemon start script for peer '{peer_id}' ({display_name})
# Generated by clade peer-ops.

set -e
cd "$(dirname "$0")"

CLADE_REPO_DIR="${{CLADE_REPO_DIR:-/opt/clade-a2a}}"
CLADE_PYTHON="$CLADE_REPO_DIR/.venv/bin/python"

if [[ ! -x "$CLADE_PYTHON" ]]; then
  echo "Error: clade-a2a not installed at $CLADE_REPO_DIR"
  exit 1
fi

export CLADE_CONFIG="$(pwd)/{peer_id}.yaml"
if [[ ! -f "$CLADE_CONFIG" ]]; then
  echo "Error: config not found at $CLADE_CONFIG"
  exit 1
fi

echo "Starting Clade A2A daemon as '{peer_id}'..."
echo "  Config: $CLADE_CONFIG"
exec "$CLADE_PYTHON" -m agent.daemon "$@"
"""


def _render_chat_sh(peer_id: str, display_name: str, relay_url: str, agent_dir: Path) -> str:
    workdir = agent_dir / f"workdir-{peer_id}"
    return f"""#!/bin/bash
# Clade A2A interactive Claude session for peer '{peer_id}' ({display_name})
# Generated by clade peer-ops.

set -e
cd "$(dirname "$0")"
WORKDIR="{workdir}"
MY_ID="{peer_id}"
MY_NAME="{display_name}"
RELAY_URL="{relay_url}"

if ! command -v claude > /dev/null; then
  echo "Error: 'claude' command not found in PATH"
  exit 1
fi
if [[ ! -d "$WORKDIR" ]]; then
  echo "Error: workdir not found at $WORKDIR"
  exit 1
fi

SYSTEM_PROMPT="You help the user talk over the Clade A2A network.
USER is peer '${{MY_NAME}}' (ID: ${{MY_ID}}). Relay: ${{RELAY_URL}}.
Use clade_peers() to see who is online, clade_message(to=, content=) for 1:1 ask,
clade_broadcast(to_team=, content=) for team-wide, clade_task(to=, brief=) for async.
Be terse — one sentence for trivial info, no tables for <5 items, no unsolicited follow-up."

cd "$WORKDIR"
exec claude --append-system-prompt "$SYSTEM_PROMPT" --permission-mode acceptEdits --allowedTools "{CLADE_TOOLS}"
"""


def _render_mcp_config(peer_id: str, agent_dir: Path) -> str:
    return json.dumps({
        "mcpServers": {
            "clade": {
                "command": "/opt/clade-a2a/.venv/bin/python",
                "args": ["/opt/clade-a2a/agent/main.py"],
                "env": {"CLADE_CONFIG": str(agent_dir / f"{peer_id}.yaml")},
            }
        }
    }, indent=2) + "\n"


# ---- helpers shared across ops ----

def _find_active_project(setup_base: Path) -> Path:
    projects = sorted(
        p for p in setup_base.iterdir()
        if p.is_dir() and (p / "setup.json").exists()
    )
    if not projects:
        raise FileNotFoundError(f"No setup project found in {setup_base}")
    if len(projects) > 1:
        listing = ", ".join(p.name for p in projects)
        raise RuntimeError(f"Multiple setup projects in {setup_base}: {listing}")
    return projects[0]


def _existing_yamls(project_dir: Path, agent_dir: Path, peer_ids: list[str]) -> list[tuple[Path, str]]:
    """Yield (path, peer_id) for every yaml that exists in either project_dir or agent_dir."""
    out: list[tuple[Path, str]] = []
    for pid in peer_ids:
        for base in (agent_dir, project_dir):
            p = base / f"{pid}.yaml"
            if p.exists():
                out.append((p, pid))
    return out


def _reload_relay(relay_url: str | None, any_bearer: str) -> dict[str, Any]:
    if not relay_url:
        return {"skipped": True}
    try:
        r = httpx.post(f"{relay_url}/admin/reload-tokens",
                        headers={"Authorization": f"Bearer {any_bearer}"}, timeout=5)
        return {"status_code": r.status_code, "body": r.json() if r.status_code == 200 else r.text[:200]}
    except Exception as e:
        return {"error": f"{type(e).__name__}: {e}"}


def _reload_setup_server(url: str | None) -> dict[str, Any]:
    if not url:
        return {"skipped": True}
    try:
        r = httpx.post(f"{url.rstrip('/')}/admin/reload", timeout=5)
        return {"status_code": r.status_code, "body": r.json() if r.status_code == 200 else r.text[:200]}
    except Exception as e:
        return {"error": f"{type(e).__name__}: {e}"}


# ---- add ----

def add_peer_op(
    project_dir: Path,
    agent_dir: Path,
    peer_id: str,
    display_name: str,
    role: str,
    teams: list[str] | None = None,
    extra_add_dirs: list[str] | None = None,
    relay_url_for_reload: str | None = None,
    setup_server_url_for_reload: str | None = None,
) -> dict[str, Any]:
    teams = teams or []
    extra_add_dirs = extra_add_dirs or []

    pid = peer_id.strip()
    if not pid or not pid[0].isalpha() or not all(c.isalnum() or c in "-_" for c in pid):
        raise ValueError("invalid peer_id (must start with a letter, alnum/dash/underscore only)")

    setup = json.loads((project_dir / "setup.json").read_text())
    tokens = json.loads((project_dir / "tokens.json").read_text())
    existing_ids = [p["peer_id"] for p in setup["peers"]]
    if pid in existing_ids:
        raise ValueError(f"peer '{pid}' already exists")

    new_bearer = secrets.token_urlsafe(32)
    new_download_token = secrets.token_urlsafe(24)
    new_pair_secrets = {other: secrets.token_hex(32) for other in existing_ids}
    role_short = role.strip().split("\n")[0][:200]

    # 1. update existing yamls
    for yaml_path, other_id in _existing_yamls(project_dir, agent_dir, existing_ids):
        data = _read_yaml(yaml_path)
        data.setdefault("peers", {})[pid] = {
            "secret": new_pair_secrets[other_id],
            "name": display_name,
            "role": role_short,
        }
        data.setdefault("teams", {})
        for t in teams:
            members = data["teams"].setdefault(t, [])
            if pid not in members:
                members.append(pid)
        _write_yaml(yaml_path, data)

    # 2. build new peer's yaml
    new_peers_dict: dict[str, Any] = {}
    for other in existing_ids:
        other_art = next(p for p in setup["peers"] if p["peer_id"] == other)
        entry: dict[str, Any] = {"secret": new_pair_secrets[other]}
        if other_art.get("display_name") and other_art["display_name"] != other:
            entry["name"] = other_art["display_name"]
        if other_art.get("role"):
            entry["role"] = other_art["role"].strip().split("\n")[0][:200]
        new_peers_dict[other] = entry

    # combined teams from any existing yaml
    combined_teams: dict[str, list[str]] = {}
    for yaml_path, _ in _existing_yamls(project_dir, agent_dir, existing_ids):
        data = _read_yaml(yaml_path)
        for tn, m in (data.get("teams") or {}).items():
            combined_teams.setdefault(tn, list(m))
        if combined_teams:
            break
    for t in teams:
        m = combined_teams.setdefault(t, [])
        if pid not in m:
            m.append(pid)

    new_yaml = {
        "my_id": pid, "name": display_name, "role": role.strip(),
        "relay_url": setup["relay_url"], "bearer_token": new_bearer,
        "peers": new_peers_dict,
        "audit_db": f"~/.clade/{pid}-audit.db",
        "extra_add_dirs": list(extra_add_dirs),
    }
    if combined_teams:
        new_yaml["teams"] = combined_teams
    yaml_text = yaml.dump(new_yaml, default_flow_style=False, allow_unicode=True, sort_keys=False)

    for base in (project_dir, agent_dir):
        if base.exists():
            (base / f"{pid}.yaml").write_text(yaml_text)
            (base / f"{pid}.yaml").chmod(0o600)

    # 3. tokens.json + setup.json
    tokens[new_bearer] = pid
    _write_json_secure(project_dir / "tokens.json", tokens)

    setup["peers"].append({
        "peer_id": pid, "display_name": display_name, "role": role,
        "download_token": new_download_token, "bearer_token": new_bearer,
        "yaml_path": str(project_dir / f"{pid}.yaml"), "yaml_content": yaml_text,
    })
    _write_json_secure(project_dir / "setup.json", setup)

    # 4. agent_dir helpers
    if agent_dir.exists():
        (agent_dir / f"start-{pid}.sh").write_text(_render_start_sh(pid, display_name))
        (agent_dir / f"start-{pid}.sh").chmod(0o755)
        (agent_dir / f"chat-{pid}.sh").write_text(_render_chat_sh(pid, display_name, setup["relay_url"], agent_dir))
        (agent_dir / f"chat-{pid}.sh").chmod(0o755)
        wd = agent_dir / f"workdir-{pid}"
        wd.mkdir(exist_ok=True)
        (wd / ".mcp.json").write_text(_render_mcp_config(pid, agent_dir))

    # 5. reload
    any_bearer = next(iter(tokens))
    relay_resp = _reload_relay(relay_url_for_reload or setup["relay_url"] if relay_url_for_reload != "" else None, any_bearer) \
        if relay_url_for_reload is not None else {"skipped": True}
    ss_resp = _reload_setup_server(setup_server_url_for_reload) if setup_server_url_for_reload is not None else {"skipped": True}

    return {
        "ok": True, "peer_id": pid, "download_token": new_download_token,
        "bearer_token": new_bearer, "added_to_teams": teams,
        "relay_reload": relay_resp, "setup_server_reload": ss_resp,
        "next_step": f"{agent_dir}/start-{pid}.sh --yolo",
    }


# ---- update ----

def update_peer_op(
    project_dir: Path,
    agent_dir: Path,
    peer_id: str,
    role: str | None = None,
    display_name: str | None = None,
    extra_add_dirs: list[str] | None = None,
    setup_server_url_for_reload: str | None = None,
) -> dict[str, Any]:
    setup = json.loads((project_dir / "setup.json").read_text())
    target_idx = next((i for i, p in enumerate(setup["peers"]) if p["peer_id"] == peer_id), None)
    if target_idx is None:
        raise ValueError(f"peer '{peer_id}' does not exist")

    fields_changed: list[str] = []
    role_short_new: str | None = None
    if role is not None:
        new_role = role.strip()
        if new_role != setup["peers"][target_idx]["role"].strip():
            setup["peers"][target_idx]["role"] = new_role
            role_short_new = new_role.split("\n")[0][:200]
            fields_changed.append("role")
    if display_name is not None:
        if display_name != setup["peers"][target_idx]["display_name"]:
            setup["peers"][target_idx]["display_name"] = display_name
            fields_changed.append("display_name")
    if extra_add_dirs is not None:
        # tracked in own yaml only
        fields_changed.append("extra_add_dirs")

    # 1. update target peer's OWN yaml (role, name, extra_add_dirs)
    own_paths = [project_dir / f"{peer_id}.yaml", agent_dir / f"{peer_id}.yaml"]
    yaml_text_new = None
    for op in own_paths:
        if not op.exists():
            continue
        data = _read_yaml(op)
        if role is not None:
            data["role"] = role.strip()
        if display_name is not None:
            data["name"] = display_name
        if extra_add_dirs is not None:
            data["extra_add_dirs"] = list(extra_add_dirs)
        _write_yaml(op, data)
        if yaml_text_new is None:
            yaml_text_new = yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False)

    # 2. update OTHER peers' yamls (their peers.<peer_id>.name/role) — for role/display_name only
    if role is not None or display_name is not None:
        other_ids = [p["peer_id"] for p in setup["peers"] if p["peer_id"] != peer_id]
        for yaml_path, _ in _existing_yamls(project_dir, agent_dir, other_ids):
            data = _read_yaml(yaml_path)
            if "peers" not in data or peer_id not in data["peers"]:
                continue
            entry = data["peers"][peer_id]
            if display_name is not None:
                entry["name"] = display_name
            if role is not None and role_short_new is not None:
                entry["role"] = role_short_new
            _write_yaml(yaml_path, data)

    # 3. setup.json yaml_content keepsake
    if yaml_text_new is not None:
        setup["peers"][target_idx]["yaml_content"] = yaml_text_new
    _write_json_secure(project_dir / "setup.json", setup)

    # 4. regenerate chat-<peer>.sh if display_name changed (it embeds the name)
    if display_name is not None and agent_dir.exists() and (agent_dir / f"chat-{peer_id}.sh").exists():
        (agent_dir / f"chat-{peer_id}.sh").write_text(
            _render_chat_sh(peer_id, display_name, setup["relay_url"], agent_dir))
        (agent_dir / f"chat-{peer_id}.sh").chmod(0o755)

    ss_resp = _reload_setup_server(setup_server_url_for_reload) if setup_server_url_for_reload is not None else {"skipped": True}

    # Daemon restart required for own-peer changes (config_watcher_loop only reloads cfg.peers,
    # NOT cfg.role / cfg.name / cfg.extra_add_dirs).
    restart_required_for: list[str] = []
    if fields_changed:
        restart_required_for.append(peer_id)
    # display_name/role changes propagate to other peers' system prompts on their next ask,
    # but their cfg.peers[peer_id].name/role IS hot-reloaded → no restart needed for them.

    return {
        "ok": True, "peer_id": peer_id, "fields_changed": fields_changed,
        "restart_required_for": restart_required_for,
        "setup_server_reload": ss_resp,
    }


# ---- remove ----

def remove_peer_op(
    project_dir: Path,
    agent_dir: Path,
    peer_id: str,
    relay_url_for_reload: str | None = None,
    setup_server_url_for_reload: str | None = None,
    kill_daemon: bool = True,
) -> dict[str, Any]:
    setup = json.loads((project_dir / "setup.json").read_text())
    target = next((p for p in setup["peers"] if p["peer_id"] == peer_id), None)
    if target is None:
        raise ValueError(f"peer '{peer_id}' does not exist")
    if len(setup["peers"]) <= 2:
        raise ValueError("cannot remove peer — at least 2 peers must remain (A2A needs a counterpart)")

    other_ids = [p["peer_id"] for p in setup["peers"] if p["peer_id"] != peer_id]

    # 1. tokens.json: drop the bearer
    tokens = json.loads((project_dir / "tokens.json").read_text())
    tokens = {b: a for b, a in tokens.items() if a != peer_id}
    _write_json_secure(project_dir / "tokens.json", tokens)

    # 2. every other yaml: remove peer from peers + from teams
    for yaml_path, _ in _existing_yamls(project_dir, agent_dir, other_ids):
        data = _read_yaml(yaml_path)
        if data.get("peers") and peer_id in data["peers"]:
            data["peers"].pop(peer_id, None)
        if data.get("teams"):
            for team_name, members in list(data["teams"].items()):
                if peer_id in members:
                    data["teams"][team_name] = [m for m in members if m != peer_id]
        _write_yaml(yaml_path, data)

    # 3. setup.json: drop the entry
    setup["peers"] = [p for p in setup["peers"] if p["peer_id"] != peer_id]
    _write_json_secure(project_dir / "setup.json", setup)

    # 4. kill daemon if running (lock file PID)
    daemon_killed = False
    lock = Path.home() / ".clade" / f"{peer_id}-daemon.lock"
    if kill_daemon and lock.exists():
        try:
            pid = int(lock.read_text().strip())
            os.kill(pid, 15)  # SIGTERM
            daemon_killed = True
        except (ValueError, ProcessLookupError, PermissionError, OSError):
            pass
        try:
            lock.unlink()
        except OSError:
            pass

    # 5. remove the peer's own files in agent_dir + project_dir
    deleted_files: list[str] = []
    candidates = [
        project_dir / f"{peer_id}.yaml",
        agent_dir / f"{peer_id}.yaml",
        agent_dir / f"start-{peer_id}.sh",
        agent_dir / f"chat-{peer_id}.sh",
    ]
    for c in candidates:
        if c.exists():
            try:
                c.unlink()
                deleted_files.append(str(c))
            except OSError:
                pass
    wd = agent_dir / f"workdir-{peer_id}"
    if wd.exists() and wd.is_dir():
        import shutil
        shutil.rmtree(wd, ignore_errors=True)
        deleted_files.append(str(wd))

    # NOTE: ~/.clade/<peer>-audit.db is intentionally LEFT (forensics).

    # 6. reload
    any_bearer = next(iter(tokens)) if tokens else ""
    relay_resp = _reload_relay(relay_url_for_reload, any_bearer) if relay_url_for_reload and any_bearer else {"skipped": True}
    ss_resp = _reload_setup_server(setup_server_url_for_reload) if setup_server_url_for_reload is not None else {"skipped": True}

    return {
        "ok": True, "removed": peer_id, "daemon_killed": daemon_killed,
        "deleted_files": deleted_files,
        "relay_reload": relay_resp, "setup_server_reload": ss_resp,
    }


# ---- teams ----

def update_teams_op(
    project_dir: Path,
    agent_dir: Path,
    teams: dict[str, list[str]],
    setup_server_url_for_reload: str | None = None,
) -> dict[str, Any]:
    setup = json.loads((project_dir / "setup.json").read_text())
    existing_ids = {p["peer_id"] for p in setup["peers"]}

    # validate: every team member must be a known peer
    invalid: dict[str, list[str]] = {}
    for tn, members in teams.items():
        bad = [m for m in members if m not in existing_ids]
        if bad:
            invalid[tn] = bad
    if invalid:
        raise ValueError(f"teams reference unknown peers: {invalid}")

    # write the full teams dict to every yaml
    for yaml_path, _ in _existing_yamls(project_dir, agent_dir, list(existing_ids)):
        data = _read_yaml(yaml_path)
        data["teams"] = {k: list(v) for k, v in teams.items()}
        _write_yaml(yaml_path, data)

    ss_resp = _reload_setup_server(setup_server_url_for_reload) if setup_server_url_for_reload is not None else {"skipped": True}
    return {"ok": True, "teams": teams, "setup_server_reload": ss_resp}
